server:
  port: 8004

spring:
  application:
    name: customers-ui

eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka

#开启feign的服务降级
feign:
  circuitbreaker:
    enabled: true

#降级响应设置超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
