server:
  port: 8001

#每个服务都要有指定的name,此name就是当前系统中服务的唯一标识(服务id)
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springdemo_01?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
      username: root
      password: 123456

  application:
    name: goods-provider


#指定当前服务注册的 '服务注册与发现中心'的地址
eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.ljh.commons.pojo
